# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbelt2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travelfrom',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travelto',
            field=models.DateField(auto_now_add=True),
        ),
    ]
